apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webserver
  template:
    metadata:
      labels:
        app: my-webserver
    spec:
      containers:
        - name: webserver
          image: mahmudakeya/spark-lms
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: my-webserver-service
spec:
  selector:
    app: my-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30050
  type: NodePort
