apiVersion: v1
kind: Service
metadata:
  name: sparklms
  namespace: sheshir-namespace
spec:
  selector:
    app: sparklms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
