apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparklms
  namespace: sheshir-namespace
spec:
  selector:
    matchLabels:
      app: sparklms
  replicas: 1
  template:
    metadata:
      labels:
        app: sparklms
    spec:
      containers:
        - name: sparklms
          image: mahmudulhasansheshir/spark
          ports:
            - containerPort: 8080
            

